-- Active: 1683147160886@@localhost@3307

CREATE DATABASE 
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    policy_terms BOOLEAN NOT NULL DEFAULT false,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

